import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const packageJson = JSON.parse(await readFile(join(root, "package.json"), "utf8"));
const projectMeta = JSON.parse(await readFile(join(root, "config/project-meta.json"), "utf8"));

const text = `# Latest Iteration Guide

\`\`\`yaml
provenance:
  authors: project_owner + Codex
  ai_assisted: true
  human_reviewed: declined
  audited_by: Mercury Lab self-audit
  audit_ref: docs/CYCLE-02-COMMITMENT.md
\`\`\`

This file is generated by \`npm run guide:latest\`. Edit the source release surfaces first, then regenerate this guide.

## Current Version

\`${packageJson.version}\` - ${projectMeta.codename || "Feature Freeze"}.

## Current Objective

Keep the project stable, narrow, and cheap to reactivate:

- start future sessions from \`MEMORY.md\`, this file, and \`docs/CYCLE-02-COMMITMENT.md\`
- run \`npm run cycle:status\` and \`npm run cycle:check\` before opening long docs
- keep the method layer case-first; \`v1.4.x\` is reserved for taxonomy, routing theory, coverage, related-work, and blueprint docs
- use \`v1.5.x\` for Human Review Checklist, START-HERE, scope, i18n, and progressive-disclosure work
- use \`v1.6.x\` for the pre-storage SDK/API, policy layer, memory-write hook demo, benchmark, and OWASP C8 mapping
- use \`v1.7.x\` for audit kernel independence, profile/standard/source/lifecycle/disagreement contracts, and Mercury Agent relationship clarity
- use \`v1.8.x\` for scenario packs, adapter contract, and scenario-aware review UX
- use \`v1.9.x\` for Proof Pack 002, rule version governance, lifecycle governance, human-review disagreement, and anti-gaming tests
- deepen proof cases, failure modes, review ledger, and real charter-user records before adding product surface
- use \`docs/START-HERE.md\` as the role-based entry point for humans and agents
- use \`docs/SCOPE.md\` before adding storage, database, or ecosystem recommendations
- use \`docs/SDK-API.md\` before adding any host adapter
- use \`docs/AUDIT-KERNEL.md\` before changing SDK behavior
- use \`docs/SCENARIO-PACKS.md\`, \`docs/ADAPTER-CONTRACT.md\`, and \`docs/REVIEW-UX-GUIDE.md\` before adding integration UX
- use \`docs/RULE-VERSION-GOVERNANCE.md\`, \`docs/MEMORY-LIFECYCLE-GOVERNANCE.md\`, \`docs/HUMAN-REVIEW-DISAGREEMENT.md\`, and \`docs/ANTI-GAMING-TESTS.md\` before changing governance rules
- use \`docs/ECOSYSTEM-POSITION.md\` and \`docs/MERCURY-AGENT-RELATIONSHIP.md\` before changing project positioning
- use \`docs/OWASP-AISVS-C8-MAPPING.md\` before making compliance-related claims
- use \`docs/AGENT-AUDIT-BLUEPRINT.md\` as the implementer-facing guide
- use \`docs/ROUTING-THEORY.md\` and \`docs/PROOF-PACK-COVERAGE-MATRIX.md\` before adding new failure modes
- use \`npm run capture -- --file <path>\` or \`npm run capture:dropzone\` to preserve AI conversation source evidence without promoting it
- use Audit Packets as the runnable unit for Agent/FDE/long-term-memory claim review
- keep Markdown/YAML as source of truth and HTML as a generated delivery layer
- run \`npm run audit\`, \`npm run audit:flow\`, and \`npm run report\` when validating evidence-first examples
- use \`npm run audit:profile\` when audit packet performance changes
- run \`npm run cycle:status\` before proof-pack or failure-mode exploration
- run \`npm run validate:incr\` before full validation when exploring
- run \`npm run index:incr\` before full indexing when exploring
- use \`npm run release:gate\` before any release or patch
- preserve the bad-memory intercept with \`routing_decision: discard\`

## Current Stop List

- Do not turn Mercury into a general Agent framework.
- Do not turn Audit Packets into a scoring/gameable success metric system.
- Do not add backend adapters.
- Do not publish an npm package until the local SDK contract survives at least one integration review.
- Do not keep judgment only in prose when it belongs in profile, standard, source, lifecycle, or disagreement contracts.
- Do not make one scenario's evidence threshold the default for every domain.
- Do not silently migrate old accepted memories to a new ruleset without a re-audit record.
- Do not let route-forcing or forged-review instructions pass as ordinary packet content.
- Do not add new product surface during method-depth work.
- Do not expose raw technical fields as the first user-visible layer when a checklist or summary can lead.
- Do not add storage backend configuration UI; document exports instead.
- Do not present Mercury as a certification authority.
- Do not add official failure modes without proof-pack or coverage-matrix support.
- Do not treat a captured conversation as approved memory.
- Do not auto-promote Lite/dropzone captures into durable project memory.
- Do not fabricate charter users or external feedback.
- Do not mark \`human_reviewed: true\` without a named human reviewer.
- Do not add AI scoring, AI self-audit, RAG, or fine-tuning audit features.
- Do not claim OWASP AISVS compliance; document mapping only.
- Do not rewrite \`00_raw\` to make later conclusions cleaner.
- Do not invent \`source_refs\` or \`audit_refs\`.

## Read Policy

- For release work, prefer \`README.md\`, \`DEMO.md\`, \`CHANGELOG.md\`, \`package.json\`, and \`config/project-meta.json\`.
- For audit-contract work, read \`docs/AUDIT-CONTRACT.md\`.
- For methodology/provenance work, read \`docs/METHODOLOGY-INTEGRITY.md\`.
- For proof-pack work, read \`docs/PROOF-PACK-001.md\` and the directly referenced artifacts.
- For Cycle 02 work, read \`docs/CYCLE-02-COMMITMENT.md\`, \`docs/FAILURE-MODES.md\`, \`docs/REVIEW-LEDGER.md\`, or \`docs/CHARTER-USER-RECORDS.md\` only as needed.
- For Audit Packet work, read \`docs/EVIDENCE-FIRST-AUDIT-LAYER.md\` and \`examples/audit-packets/\`.
- For detailed v0.9 history, read \`docs/ITERATION-GUIDE-0.9.md\` by section, not as the default first step.

## Validation

\`\`\`powershell
npm run validate:incr
npm run cycle:status
npm run cycle:check
npm run capture:check
npm run test:sdk
npm run demo:memory-hook
npm run benchmark:audit
npm run index:incr
npm run audit
npm run audit:flow
npm run report
npm run test
npm run audit:profile
npm run release:gate
\`\`\`
`;

await writeFile(join(root, "docs", "ITERATION-GUIDE-LATEST.md"), text, "utf8");
console.log(`Wrote docs/ITERATION-GUIDE-LATEST.md for ${packageJson.version}`);
