import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const packageJson = JSON.parse(await readFile(join(root, "package.json"), "utf8"));
const projectMeta = JSON.parse(await readFile(join(root, "config/project-meta.json"), "utf8"));

const text = `# Latest Iteration Guide

\`\`\`yaml
provenance:
  authors: project_owner + Codex
  ai_assisted: true
  human_reviewed: pending
  audited_by: Mercury Lab self-audit
  audit_ref: docs/ITERATION-HANDOFF-1.0.0.md
\`\`\`

This file is generated by \`npm run guide:latest\`. Edit the source release surfaces first, then regenerate this guide.

## Current Version

\`${packageJson.version}\` - ${projectMeta.codename || "Feature Freeze"}.

## Current Objective

Keep the project stable and cheap to reactivate:

- start future sessions from \`MEMORY.md\`, this file, and \`docs/CHECKLIST-REACTIVATION.md\`
- run \`npm run validate:incr\` before full validation when exploring
- run \`npm run index:incr\` before full indexing when exploring
- use \`npm run release:gate\` before any release or patch
- preserve the bad-memory intercept with \`routing_decision: discard\`

## Current Stop List

- Do not add non-critical features during \`1.0.x\`.
- Do not add new artifact types.
- Do not add backend adapters.
- Do not add AI scoring, AI self-audit, RAG, or fine-tuning audit features.
- Do not rewrite \`00_raw\` to make later conclusions cleaner.
- Do not invent \`source_refs\` or \`audit_refs\`.

## Read Policy

- For release work, prefer \`README.md\`, \`DEMO.md\`, \`CHANGELOG.md\`, \`package.json\`, and \`config/project-meta.json\`.
- For audit-contract work, read \`docs/AUDIT-CONTRACT.md\`.
- For methodology/provenance work, read \`docs/METHODOLOGY-INTEGRITY.md\`.
- For detailed v0.9 history, read \`docs/ITERATION-GUIDE-0.9.md\` by section, not as the default first step.

## Validation

\`\`\`powershell
npm run validate:incr
npm run index:incr
npm run release:gate
\`\`\`
`;

await writeFile(join(root, "docs", "ITERATION-GUIDE-LATEST.md"), text, "utf8");
console.log(`Wrote docs/ITERATION-GUIDE-LATEST.md for ${packageJson.version}`);
