import { mkdir, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { auditPackets } from "./audit-core/audit_rules.mjs";
import { readAuditPackets, readKnownPaths } from "./audit-core/packet_io.mjs";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const outputRoot = join(root, "dist", "memory-flow");
const [packets, knownPaths] = await Promise.all([
  readAuditPackets(root),
  readKnownPaths(root)
]);
const audit = auditPackets(packets, { knownPaths });

await rm(outputRoot, { recursive: true, force: true });
await mkdir(outputRoot, { recursive: true });

for (const result of audit.results) {
  const target = join(root, ...result.routing_target.split("/"));
  await mkdir(target, { recursive: true });
  await writeFile(
    join(target, `${safeFileName(result.packet_id)}.json`),
    `${JSON.stringify(toFlowRecord(result), null, 2)}\n`,
    "utf8"
  );
}

await writeFile(join(outputRoot, "README.md"), renderIndex(audit), "utf8");

console.log(`Simulated memory flow for ${audit.summary.total} packet(s)`);
console.log("Wrote dist/memory-flow/README.md");

function toFlowRecord(result) {
  return {
    packet_id: result.packet_id,
    title: result.packet_title,
    routing_decision: result.routing_decision,
    routing_target: result.routing_target,
    blockers: result.blockers.map((blocker) => blocker.id),
    required_fixes: result.required_fixes,
    required_evidence: result.required_evidence,
    human_review_required: result.human_review_required
  };
}

function renderIndex(auditResult) {
  const rows = auditResult.results.map((result) => (
    `| ${result.packet_id} | ${result.routing_decision} | ${result.routing_target} | ${result.blockers.map((blocker) => blocker.id).join(", ") || "none"} |`
  )).join("\n");

  return `# Simulated Memory Flow

Generated by \`npm run audit:flow\`.

| Packet | Decision | Target | Blockers |
|---|---|---|---|
${rows}
`;
}

function safeFileName(value) {
  return String(value || "packet").replace(/[^A-Za-z0-9_-]+/g, "-");
}
